### ISSUE TITLE
HTTPS support

### ISSUE THREAD

**Issue by MicahZoltu** [circlingthesun/systemjs-script-plugin#2]
This doesn't appear to work for HTTPS endpoints.

```
import stripeCheckout from 'https://checkout.stripe.com/checkout.js!system-script';
```

Results in:

```
GET http://https//checkout.stripe.com/checkout.js net::ERR_NAME_NOT_RESOLVED
```

**Comment by circlingthesun** [comment]
Unfortunately I could not get the version of systemjs I wrote this for to
accept the protocol prefix. If you leave out the "https://" prefix it
should default to https if your site is served over https. This plugin
should no longer be required in the next version or the recently released
version of systemjs, which should also support specifying a protocol prefix
if I'm not mistaken.

**Comment by MicahZoltu** [comment]
I was unable to figure out how to make this work in the latest version of SystemJS (which according to some very old GitHub issues should solve it).  Unfortunately, the resource is from a third party and must be fetched over HTTPS but my site may be fetched over HTTP.

I have worked around this by setting up a proxy server, so I'm no longer under pressure to see this resolved and if you believe it isn't worth the work I won't take offense if you close this ticket.

**Comment by circlingthesun** [comment]
Have you had a look at this fork: https://github.com/rich-nguyen/systemjs-script-plugin?

**Comment by MicahZoltu** [comment]
I ended up taking a different route to solving this problem.  Unfortunately, the module in question is a global module so this technique results in polluting the global scope (undesirable).
